<?php

/**
 * Sample client code:
 * 
 * $connection = sync_postgis_get_postgis_connection();
 * $query = new syncPgQuery($connection, '900913');
 * $geom = 'POLYGON((-121.748434435966 54.4439949294269,-119.001852405208 54.4439949294269,-119.001852405208
 * 56.7703201938044,-121.748434435966 56.7703201938044,-121.748434435966 54.4439949294269))';
 * try {
 *   $sql = $query
 *     ->entityCondition('entity_type', 'node')
 *     ->entityCondition('bundle', 'road')
 *     ->fieldCondition('field_district', 'field_district', 740)
 *     ->addFields(array('field_road_status'))
 *     ->addGeometry()
 *     ->geometryCondition('within', $geom)
 *     ->getSql();
 * }
 * catch(Exception $e) {
 *   watchdog_exception('sync_postgis_query', $e);
 * }
 *
 */